apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beluga-data-ingress
  namespace: beluga-data
spec:
  rules:
    - host: trino.local.beluga.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trino
                port:
                  number: 8080
    - host: airflow.local.beluga.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airflow
                port:
                  number: 8080
    - host: superset.local.beluga.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: superset
                port:
                  number: 8088
    - host: catalog.local.beluga.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lakekeeper
                port:
                  number: 8181
    - host: s3.local.beluga.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-s3
                port:
                  number: 8333
    - host: filer.local.beluga.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-s3
                port:
                  number: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beluga-argocd-ingress
  namespace: argocd
spec:
  rules:
    - host: argocd.local.beluga.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
